
name = "DashTextAnnotate"
uuid = "1b08a953-4be3-4667-9a23-f716ac6520f2"
authors = ["Sebastian Nichtern <sebastian.nichtern@gmail.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
