import {build} from 'esbuild';
import {readFile, writeFile, readdir} from 'node:fs/promises';
import {parse} from 'react-docgen';

// Use Dash's React instance. Bundling another React breaks hook dispatch.
const dashGlobals = {
  name: 'dash-globals',
  setup(builder) {
    builder.onResolve({filter: /^(react|react-dom|prop-types)$/}, args => ({
      path: args.path, namespace: 'dash-global',
    }));
    builder.onLoad({filter: /.*/, namespace: 'dash-global'}, args => ({
      contents: `module.exports = window.${{'react': 'React', 'react-dom': 'ReactDOM', 'prop-types': 'PropTypes'}[args.path]};`,
    }));
  },
};

const result = await build({
  entryPoints: ['src/lib/index.js'],
  outfile: 'dash_text_annotate/dash_text_annotate.min.js',
  bundle: true,
  minify: true,
  format: 'iife',
  globalName: 'dash_text_annotate',
  target: ['es2022'],
  loader: {'.js': 'jsx'},
  plugins: [dashGlobals],
  define: {'process.env.NODE_ENV': '"production"'},
  legalComments: 'inline',
  metafile: true,
});
if (Object.keys(result.metafile.inputs).some(name => /node_modules\/react\//.test(name))) {
  throw new Error('React must be provided by Dash, not bundled.');
}
await writeFile('dash_text_annotate/package-info.json', await readFile('package.json'));
const componentPath = 'src/lib/components/DashTextAnnotate.react.js';
const [metadata] = parse(await readFile(componentPath, 'utf8'), {
  filename: componentPath, babelOptions: {babelrc: false, configFile: false},
});
await writeFile('dash_text_annotate/metadata.json', JSON.stringify({[componentPath]: metadata}));

// Retain full license notices for every package actually included in the bundle.
const packages = new Set(Object.keys(result.metafile.inputs).flatMap(path => {
  const match = path.match(/^node_modules\/(\@[^/]+\/[^/]+|[^/]+)/);
  return match ? [match[1]] : [];
}));
const missingLicenses = {'@recogito/text-annotator': 'recogito', '@annotorious/core': 'annotorious'};
let notices = '# Third-party notices\n\nGenerated by `npm run build` from bundled packages. React and PropTypes are provided by Dash.\n';
for (const name of [...packages].sort()) {
  const directory = `node_modules/${name}`;
  const info = JSON.parse(await readFile(`${directory}/package.json`, 'utf8'));
  const files = await readdir(directory);
  const file = files.find(file => /^licen[cs]e(\.|$)/i.test(file));
  const license = await readFile(file ? `${directory}/${file}` : `licenses/${missingLicenses[name]}.txt`, 'utf8');
  notices += `\n## ${name} ${info.version} (${info.license})\n\n${license.trim()}\n`;
}
await writeFile('THIRD_PARTY_NOTICES.md', notices);
await writeFile('dash_text_annotate/THIRD_PARTY_NOTICES.md', notices);
